spring:
  application:
    name: user-api
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: welcome123

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
message: test

