spring:
  application:
    name: user-api
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: welcome123
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
message: test

